---

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled

- name: Set UFW default outgoing policy to deny
  ansible.builtin.ufw:
    direction: outgoing
    policy: deny
  notify: Restart UFW
