---

- name: Include prereqs tasks
  ansible.builtin.include_tasks: prereqs.yml

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml

- name: Include service tasks
  ansible.builtin.include_tasks: service.yml
