---

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
      - lib32gcc-s1
      - lib32stdc++6
      - screen
      - curl
    state: present

- name: Create SteamCMD directory
  ansible.builtin.file:
    path: /opt/steamcmd
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Install | Add i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386

- name: Accept steam license
  ansible.builtin.debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: Install SteamCMD
  ansible.builtin.apt:
    name: steamcmd
    update_cache: true
